minor changes:
- more informative error message when negative durations occur
- added some activity names and introduced 'social meeting', note that I used
  to code 'meeting with everyone' as social, so this needs to be sorted out
  such that it does not occurr under meetings with individuals anymore
- added alternative project names for DBPDM paper

error: occurs when project analysis is run, needs fixing